#!/usr/bin/env bash
# A Bash script that disps the time for 12 hrs and 59 mins:
#    display hrs from 0 to 12
#    display mins from 1 to 59

i="0"
while [ $i -le 12 ]
do
echo "Hour: $i"
j="1"
while [ $j -le 59 ]
do
echo "$j"
j=$((j+1))
done
i=$((i+1))
done
